
import re
import io
from typing import Any
from reportlab.lib.pagesizes import LETTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch

def generate_tnfd_pdf(site_data: dict[str, Any], compliance_text: str) -> bytes:
    """Generate a PDF report for TNFD compliance."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=LETTER,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=18)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', alignment=1))
    
    # Custom colors
    brand_blue = colors.Color(91/255, 155/255, 213/255)
    
    # Content elements
    elements = []
    
    # Header
    header_text = f"<b>NEREUS TNFD DISCLOSURE REPORT</b>"
    elements.append(Paragraph(header_text, styles['Heading1']))
    elements.append(Spacer(1, 12))
    
    # Site Info
    site_name = site_data.get("name", "Unknown Site")
    site_loc = f"{site_data.get('region', '')}, {site_data.get('country', '')}"
    
    elements.append(Paragraph(f"<b>Site:</b> {site_name}", styles['Normal']))
    elements.append(Paragraph(f"<b>Location:</b> {site_loc}", styles['Normal']))
    elements.append(Paragraph(f"<b>Primary Habitat:</b> {site_data.get('primary_habitat', 'N/A').replace('_', ' ').title()}", styles['Normal']))
    elements.append(Spacer(1, 24))
    
    # Compliance Text
    # The literal text might contain markdown, we need to clean it up slightly for ReportLab or just dump it.
    # ReportLab Paragraph supports basic XML tags like <b>, <i>.
    # For this POC, we'll strip markdown or just render as plain text. 
    # Actually, let's just make it a big block of text.
    
    elements.append(Paragraph("<b>TNFD Compliance Assessment</b>", styles['Heading2']))
    elements.append(Spacer(1, 12))
    
    # Split text by newlines and create paragraphs
    for line in compliance_text.split('\n'):
        if line.strip():
            # Basic markdown to HTML-ish conversion for ReportLab
            clean_line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
            # Handle headers from markdown
            if clean_line.startswith('# '):
                elements.append(Paragraph(clean_line[2:], styles['Heading2']))
            elif clean_line.startswith('## '):
                elements.append(Paragraph(clean_line[3:], styles['Heading3']))
            elif clean_line.startswith('- '):
                 elements.append(Paragraph(f"• {clean_line[2:]}", styles['Normal']))
            else:
                elements.append(Paragraph(clean_line, styles['Normal']))
            elements.append(Spacer(1, 6))

    # Disclaimer
    elements.append(Spacer(1, 36))
    notice = ("<b>DISCLAIMER:</b> This report is generated by Nereus AI for demonstration purposes only. "
              "It does not constitute financial or legal advice. Verify all data independently.")
    elements.append(Paragraph(notice, styles['Italic']))

    # Build
    doc.build(elements)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
